---
StackName: instagram-bots
StackOutputKeys:
  SecretARN: InstagramBotVariousSecrets
  SharedS3Bucket: InstagramBotSharedS3Bucket
  DynamoDBTable: InstagramBotDynamoDBTable
DisableInstagram: False
Bots:
  ImgurBots:
    - Name: DogPicsBot
      DynamoDBTopic: dog-pics
      HashTags:
        - dog
        - pet
        - reddit
        - imgur
      InstagramAccountSecretKeys:
        UserName: DOGPICS_INSTAGRAM_USERNAME
        Password: DOGPICS_INSTAGRAM_PASSWORD
        S3Prefix: DOGPICS_S3_PREFIX
        ChallengeEmail: DOGPICS_CHALLENGE_EMAIL
        ChallengePass: DOGPICS_CHALLENGE_PASS
      Subreddit: rarepuppers
    - Name: EarthPicsBot
      DynamoDBTopic: earth-pics
      HashTags:
        - earth
        - earthpics
        - reddit
        - imgur
      InstagramAccountSecretKeys:
        UserName: EARTHPICS_INSTAGRAM_USERNAME
        Password: EARTHPICS_INSTAGRAM_PASSWORD
        S3Prefix: EARTHPICS_S3_PREFIX
        ChallengeEmail: EARTHPICS_CHALLENGE_EMAIL
        ChallengePass: EARTHPICS_CHALLENGE_PASS
      Subreddit: EarthPorn
  NASABot:
    Name: NASABot
    InstagramAccountSecretKeys:
      UserName: NASA_INSTAGRAM_USERNAME
      Password: NASA_INSTAGRAM_PASSWORD
      S3Prefix: NASA_S3_PREFIX
      APODKey: NASA_APOD_API_KEY
      ChallengeEmail: NASA_CHALLENGE_EMAIL
      ChallengePass: NASA_CHALLENGE_PASS
    DynamoDBTopic: nasa-pics
    HashTags:
      - nasa
      - space
      - explore
