AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: instagram-bot base stack

Resources:

  InstagramBotSharedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-shared-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: S3
  
  InstagramBotRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: True
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                  "rulePriority": 1,
                  "description": "Delete untagged images",
                  "selection": {
                      "tagStatus": "untagged",
                      "countType": "imageCountMoreThan",
                      "countNumber": 1
                  },
                  "action": {
                      "type": "expire"
                  }
              }
            ]
          }
      RepositoryName: !Sub ${AWS::StackName}-repo
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: ECR
  
  InstagramBotServerlessFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-instagram-bot-serverless-function-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref InstagramBotVariousSecrets
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - !GetAtt InstagramBotSharedS3Bucket.Arn
                  - !Sub ${InstagramBotSharedS3Bucket.Arn}/*
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:UpdateItem"
                Resource: !GetAtt InstagramBotDynamoDB.Arn

  InstagramBotServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: 
        - x86_64
      Description: Search for new images and handle them if found.
      Environment:
        Variables:
          INSTAGRAM_SECRET_ARN: !Ref InstagramBotVariousSecrets
          SHARED_S3_BUCKET: !Ref InstagramBotSharedS3Bucket
          DYNAMO_DB_TABLE: !Ref InstagramBotDynamoDB
      Events:
        ScheduleEvent:
          Properties:
            Description: Serverless Function trigger mechanism.
            Enabled: true
            Name: !Sub ${AWS::StackName}-serverless-function-event-trigger
            Schedule: 'rate(6 hours)'
          Type: Schedule
      FunctionName: !Sub ${AWS::StackName}-serverless-function
      ImageUri: !Sub ${InstagramBotRepository.RepositoryUri}:latest
      PackageType: Image
      Role: !GetAtt InstagramBotServerlessFunctionRole.Arn
      Tags:
        Stack: !Sub ${AWS::StackName}
        Resource: ECR
      Timeout: 300

  InstagramBotUserGroup:
    Type: AWS::IAM::Group
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      GroupName: InstagramBots
      Policies: 
        - PolicyName: !Sub ${AWS::StackName}-user-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource: !GetAtt InstagramBotSharedS3Bucket.Arn
  
  InstagramBotUser:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      Groups: 
        - !Ref InstagramBotUserGroup
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser
      UserName: !Sub ${AWS::StackName}-user

  InstagramBotUserAccessKey:
    Type: AWS::IAM::AccessKey
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Status: Active
      UserName: !Ref InstagramBotUser
  
  InstagramBotUserCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Access and Secret keys for the InstagramBot.
      Name: !Sub ${AWS::StackName}-user-account-secrets
      SecretString: !Sub |
        '{
          "USER_NAME":"${InstagramBotUser}",
          "ACCESS_KEY":"${InstagramBotUserAccessKey}",
          "SECRET_KEY":"${InstagramBotUserAccessKey.SecretAccessKey}"
        }'
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser
  
  InstagramBotVariousSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Various Keys needed by the InstagramBot.
      Name: !Sub ${AWS::StackName}-user-various-secrets
      SecretString: '{}'
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser
  
  InstagramBotDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
        - AttributeName: file
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: file
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableClass: STANDARD
      TableName: !Sub ${AWS::StackName}-dyanmodb-table
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: DynamoDB

  GitHubUserGroup:
    Type: AWS::IAM::Group
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      GroupName: InstagramBotsGitHubUserGroup
      Policies: 
        - PolicyName: !Sub ${AWS::StackName}-github-user-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:CompleteLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                Resource: !GetAtt InstagramBotRepository.Arn
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                Resource: !GetAtt InstagramBotServerlessFunction.Arn
  
  GitHubUser:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      Groups: 
        - !Ref GitHubUserGroup
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser
      UserName: !Sub ${AWS::StackName}-github-user

  GitHubUserAccessKey:
    Type: AWS::IAM::AccessKey
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Status: Active
      UserName: !Ref GitHubUser
  
  GitHubUserCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Access and Secret keys for the GitHub InstagramBot.
      Name: !Sub ${AWS::StackName}-github-user-account-secrets
      SecretString: !Sub |
        '{
          "USER_NAME":"${GitHubUser}",
          "ACCESS_KEY":"${GitHubUserAccessKey}",
          "SECRET_KEY":"${GitHubUserAccessKey.SecretAccessKey}"
        }'
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser

Outputs:
  InstagramBotUser:
    Description: The IAM User of the Instagram bot stack.
    Value: !Ref InstagramBotUser
  InstagramBotUserCredentials:
    Description: Access and Secret key for the Instagram bot.
    Value: !Ref InstagramBotUserCredentialsSecret
  InstagramBotRepository:
    Description: Repository of Instagram bot's Lambda code.
    Value: !Ref InstagramBotRepository
  InstagramBotVariousSecrets:
      Description: Various Keys needed by the InstagramBot.
      Value: !Ref InstagramBotVariousSecrets
  InstagramBotSharedS3Bucket:
      Description: Shared S3 bucket used by the InstagramBot.
      Value: !Ref InstagramBotSharedS3Bucket
  InstagramBotDynamoDBTable:
      Description: Shared DynamoDB Table used by the InstagramBot.
      Value: !Ref InstagramBotDynamoDB
