AWSTemplateFormatVersion: "2010-09-09"
Description: Base stack

Resources:

  InstagramBotSharedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-shared-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: S3

  InstagramBotUserGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: InstagramBots
      Policies: 
        - PolicyName: !Sub ${AWS::StackName}-user-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource: !GetAtt InstagramBotSharedS3Bucket.Arn
  
  InstagramBotUser:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
        - !Ref InstagramBotUserGroup
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser
      UserName: !Sub ${AWS::StackName}-user

  InstagramBotUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref InstagramBotUser
  
  InstagramBotUserCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Description: Access and Secret keys for the InstagramBot.
      Name: !Sub ${AWS::StackName}-instagram-bot-secret
      SecretString: !Sub |
        '{
          "USER_NAME":"${InstagramBotUser}",
          "ACCESS_KEY":"${InstagramBotUserAccessKey}",
          "SECRET_KEY":"${InstagramBotUserAccessKey.SecretAccessKey}"
        }'
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Resource
          Value: IAMUser

Outputs:
  InstagramBotUser:
    Description: The IAM User of the Instagram stack.
    Value: !Ref InstagramBotUser
  InstagramBotUserCredentials:
    Description: Access and Secret key for the Instagram bot.
    Value: !Ref InstagramBotUserCredentialsSecret

