name: Build And Deploy
on:
  push:
    branches:
      - development
      - main
    paths:
      - app/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy the Docker image
      working-directory: app
      run: |
        image="${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/instagram-bots-repo:latest"
        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
        docker build -t instagram-bots-repo .
        docker tag instagram-bots-repo:latest $image
        docker push $image
        aws lambda update-function-code --function-name instagram-bots-serverless-function --image-uri $image
      env:
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DOCKER_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DOCKER_SECRET_KEY }}
